/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as FindVansRouteImport } from './routes/find-vans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverRegisterRouteImport } from './routes/driver/register'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as BookVanIdIndexRouteImport } from './routes/book/$vanId/index'
import { Route as BookVanIdConfirmationRouteImport } from './routes/book/$vanId/confirmation'
import { Route as BookVanIdCheckoutRouteImport } from './routes/book/$vanId/checkout'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const FindVansRoute = FindVansRouteImport.update({
  id: '/find-vans',
  path: '/find-vans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRegisterRoute = DriverRegisterRouteImport.update({
  id: '/driver/register',
  path: '/driver/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVanIdIndexRoute = BookVanIdIndexRouteImport.update({
  id: '/book/$vanId/',
  path: '/book/$vanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVanIdConfirmationRoute = BookVanIdConfirmationRouteImport.update({
  id: '/book/$vanId/confirmation',
  path: '/book/$vanId/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVanIdCheckoutRoute = BookVanIdCheckoutRouteImport.update({
  id: '/book/$vanId/checkout',
  path: '/book/$vanId/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-vans': typeof FindVansRoute
  '/my-bookings': typeof MyBookingsRoute
  '/schedules': typeof SchedulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/driver/register': typeof DriverRegisterRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/book/$vanId/': typeof BookVanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-vans': typeof FindVansRoute
  '/my-bookings': typeof MyBookingsRoute
  '/schedules': typeof SchedulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/driver/register': typeof DriverRegisterRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/book/$vanId': typeof BookVanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-vans': typeof FindVansRoute
  '/my-bookings': typeof MyBookingsRoute
  '/schedules': typeof SchedulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/driver/register': typeof DriverRegisterRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/book/$vanId/': typeof BookVanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-vans'
    | '/my-bookings'
    | '/schedules'
    | '/sign-in'
    | '/sign-up'
    | '/admin/drivers'
    | '/driver/register'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/book/$vanId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-vans'
    | '/my-bookings'
    | '/schedules'
    | '/sign-in'
    | '/sign-up'
    | '/admin/drivers'
    | '/driver/register'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/book/$vanId'
  id:
    | '__root__'
    | '/'
    | '/find-vans'
    | '/my-bookings'
    | '/schedules'
    | '/sign-in'
    | '/sign-up'
    | '/admin/drivers'
    | '/driver/register'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/book/$vanId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindVansRoute: typeof FindVansRoute
  MyBookingsRoute: typeof MyBookingsRoute
  SchedulesRoute: typeof SchedulesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AdminDriversRoute: typeof AdminDriversRoute
  DriverRegisterRoute: typeof DriverRegisterRoute
  BookVanIdCheckoutRoute: typeof BookVanIdCheckoutRoute
  BookVanIdConfirmationRoute: typeof BookVanIdConfirmationRoute
  BookVanIdIndexRoute: typeof BookVanIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-vans': {
      id: '/find-vans'
      path: '/find-vans'
      fullPath: '/find-vans'
      preLoaderRoute: typeof FindVansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/register': {
      id: '/driver/register'
      path: '/driver/register'
      fullPath: '/driver/register'
      preLoaderRoute: typeof DriverRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vanId/': {
      id: '/book/$vanId/'
      path: '/book/$vanId'
      fullPath: '/book/$vanId/'
      preLoaderRoute: typeof BookVanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vanId/confirmation': {
      id: '/book/$vanId/confirmation'
      path: '/book/$vanId/confirmation'
      fullPath: '/book/$vanId/confirmation'
      preLoaderRoute: typeof BookVanIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vanId/checkout': {
      id: '/book/$vanId/checkout'
      path: '/book/$vanId/checkout'
      fullPath: '/book/$vanId/checkout'
      preLoaderRoute: typeof BookVanIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindVansRoute: FindVansRoute,
  MyBookingsRoute: MyBookingsRoute,
  SchedulesRoute: SchedulesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AdminDriversRoute: AdminDriversRoute,
  DriverRegisterRoute: DriverRegisterRoute,
  BookVanIdCheckoutRoute: BookVanIdCheckoutRoute,
  BookVanIdConfirmationRoute: BookVanIdConfirmationRoute,
  BookVanIdIndexRoute: BookVanIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
