/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as FindVansRouteImport } from './routes/find-vans'
import { Route as SuperadminRouteRouteImport } from './routes/superadmin/route'
import { Route as MyDeliveriesRouteRouteImport } from './routes/my-deliveries/route'
import { Route as DriverRouteRouteImport } from './routes/driver/route'
import { Route as ArticlesRouteRouteImport } from './routes/articles/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SendPackageIndexRouteImport } from './routes/send-package/index'
import { Route as MyDeliveriesIndexRouteImport } from './routes/my-deliveries/index'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin/users'
import { Route as SuperadminTripsRouteImport } from './routes/superadmin/trips'
import { Route as SuperadminDriversRouteImport } from './routes/superadmin/drivers'
import { Route as SuperadminBookingsRouteImport } from './routes/superadmin/bookings'
import { Route as DriverWalletRouteImport } from './routes/driver/wallet'
import { Route as DriverRegisterRouteImport } from './routes/driver/register'
import { Route as DriverCreateRouteImport } from './routes/driver/create'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTripsRouteImport } from './routes/admin/trips'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as DriverTripsRouteRouteImport } from './routes/driver/trips/route'
import { Route as SendPackageVanIdIndexRouteImport } from './routes/send-package/$vanId/index'
import { Route as DriverTripsIndexRouteImport } from './routes/driver/trips/index'
import { Route as BookVanIdIndexRouteImport } from './routes/book/$vanId/index'
import { Route as SendPackageVanIdConfirmationRouteImport } from './routes/send-package/$vanId/confirmation'
import { Route as SendPackageVanIdCheckoutRouteImport } from './routes/send-package/$vanId/checkout'
import { Route as MyDeliveriesDeliveryIdPayRouteImport } from './routes/my-deliveries/$deliveryId/pay'
import { Route as BookVanIdConfirmationRouteImport } from './routes/book/$vanId/confirmation'
import { Route as BookVanIdCheckoutRouteImport } from './routes/book/$vanId/checkout'
import { Route as DriverTripsTripIdIndexRouteImport } from './routes/driver/trips/$tripId/index'
import { Route as DriverTripsTripIdEditRouteImport } from './routes/driver/trips/$tripId/edit'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const FindVansRoute = FindVansRouteImport.update({
  id: '/find-vans',
  path: '/find-vans',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRouteRoute = SuperadminRouteRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDeliveriesRouteRoute = MyDeliveriesRouteRouteImport.update({
  id: '/my-deliveries',
  path: '/my-deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRouteRoute = DriverRouteRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRouteRoute = ArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SendPackageIndexRoute = SendPackageIndexRouteImport.update({
  id: '/send-package/',
  path: '/send-package/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDeliveriesIndexRoute = MyDeliveriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyDeliveriesRouteRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SuperadminTripsRoute = SuperadminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SuperadminDriversRoute = SuperadminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SuperadminBookingsRoute = SuperadminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const DriverWalletRoute = DriverWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverRegisterRoute = DriverRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverCreateRoute = DriverCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DriverRouteRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DriverTripsRouteRoute = DriverTripsRouteRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DriverRouteRoute,
} as any)
const SendPackageVanIdIndexRoute = SendPackageVanIdIndexRouteImport.update({
  id: '/send-package/$vanId/',
  path: '/send-package/$vanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsIndexRoute = DriverTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverTripsRouteRoute,
} as any)
const BookVanIdIndexRoute = BookVanIdIndexRouteImport.update({
  id: '/book/$vanId/',
  path: '/book/$vanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SendPackageVanIdConfirmationRoute =
  SendPackageVanIdConfirmationRouteImport.update({
    id: '/send-package/$vanId/confirmation',
    path: '/send-package/$vanId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SendPackageVanIdCheckoutRoute =
  SendPackageVanIdCheckoutRouteImport.update({
    id: '/send-package/$vanId/checkout',
    path: '/send-package/$vanId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyDeliveriesDeliveryIdPayRoute =
  MyDeliveriesDeliveryIdPayRouteImport.update({
    id: '/$deliveryId/pay',
    path: '/$deliveryId/pay',
    getParentRoute: () => MyDeliveriesRouteRoute,
  } as any)
const BookVanIdConfirmationRoute = BookVanIdConfirmationRouteImport.update({
  id: '/book/$vanId/confirmation',
  path: '/book/$vanId/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVanIdCheckoutRoute = BookVanIdCheckoutRouteImport.update({
  id: '/book/$vanId/checkout',
  path: '/book/$vanId/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsTripIdIndexRoute = DriverTripsTripIdIndexRouteImport.update({
  id: '/$tripId/',
  path: '/$tripId/',
  getParentRoute: () => DriverTripsRouteRoute,
} as any)
const DriverTripsTripIdEditRoute = DriverTripsTripIdEditRouteImport.update({
  id: '/$tripId/edit',
  path: '/$tripId/edit',
  getParentRoute: () => DriverTripsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/driver': typeof DriverRouteRouteWithChildren
  '/my-deliveries': typeof MyDeliveriesRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/find-vans': typeof FindVansRoute
  '/my-bookings': typeof MyBookingsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedules': typeof SchedulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/driver/trips': typeof DriverTripsRouteRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/driver/create': typeof DriverCreateRoute
  '/driver/register': typeof DriverRegisterRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/superadmin/bookings': typeof SuperadminBookingsRoute
  '/superadmin/drivers': typeof SuperadminDriversRoute
  '/superadmin/trips': typeof SuperadminTripsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/my-deliveries/': typeof MyDeliveriesIndexRoute
  '/send-package/': typeof SendPackageIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/my-deliveries/$deliveryId/pay': typeof MyDeliveriesDeliveryIdPayRoute
  '/send-package/$vanId/checkout': typeof SendPackageVanIdCheckoutRoute
  '/send-package/$vanId/confirmation': typeof SendPackageVanIdConfirmationRoute
  '/book/$vanId/': typeof BookVanIdIndexRoute
  '/driver/trips/': typeof DriverTripsIndexRoute
  '/send-package/$vanId/': typeof SendPackageVanIdIndexRoute
  '/driver/trips/$tripId/edit': typeof DriverTripsTripIdEditRoute
  '/driver/trips/$tripId/': typeof DriverTripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-vans': typeof FindVansRoute
  '/my-bookings': typeof MyBookingsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedules': typeof SchedulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/driver/create': typeof DriverCreateRoute
  '/driver/register': typeof DriverRegisterRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/superadmin/bookings': typeof SuperadminBookingsRoute
  '/superadmin/drivers': typeof SuperadminDriversRoute
  '/superadmin/trips': typeof SuperadminTripsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/driver': typeof DriverIndexRoute
  '/my-deliveries': typeof MyDeliveriesIndexRoute
  '/send-package': typeof SendPackageIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/my-deliveries/$deliveryId/pay': typeof MyDeliveriesDeliveryIdPayRoute
  '/send-package/$vanId/checkout': typeof SendPackageVanIdCheckoutRoute
  '/send-package/$vanId/confirmation': typeof SendPackageVanIdConfirmationRoute
  '/book/$vanId': typeof BookVanIdIndexRoute
  '/driver/trips': typeof DriverTripsIndexRoute
  '/send-package/$vanId': typeof SendPackageVanIdIndexRoute
  '/driver/trips/$tripId/edit': typeof DriverTripsTripIdEditRoute
  '/driver/trips/$tripId': typeof DriverTripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/driver': typeof DriverRouteRouteWithChildren
  '/my-deliveries': typeof MyDeliveriesRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/find-vans': typeof FindVansRoute
  '/my-bookings': typeof MyBookingsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedules': typeof SchedulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/driver/trips': typeof DriverTripsRouteRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/driver/create': typeof DriverCreateRoute
  '/driver/register': typeof DriverRegisterRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/superadmin/bookings': typeof SuperadminBookingsRoute
  '/superadmin/drivers': typeof SuperadminDriversRoute
  '/superadmin/trips': typeof SuperadminTripsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/my-deliveries/': typeof MyDeliveriesIndexRoute
  '/send-package/': typeof SendPackageIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/my-deliveries/$deliveryId/pay': typeof MyDeliveriesDeliveryIdPayRoute
  '/send-package/$vanId/checkout': typeof SendPackageVanIdCheckoutRoute
  '/send-package/$vanId/confirmation': typeof SendPackageVanIdConfirmationRoute
  '/book/$vanId/': typeof BookVanIdIndexRoute
  '/driver/trips/': typeof DriverTripsIndexRoute
  '/send-package/$vanId/': typeof SendPackageVanIdIndexRoute
  '/driver/trips/$tripId/edit': typeof DriverTripsTripIdEditRoute
  '/driver/trips/$tripId/': typeof DriverTripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/driver'
    | '/my-deliveries'
    | '/superadmin'
    | '/find-vans'
    | '/my-bookings'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/schedules'
    | '/sign-in'
    | '/sign-up'
    | '/support'
    | '/terms-of-service'
    | '/driver/trips'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/trips'
    | '/admin/users'
    | '/admin/wallets'
    | '/articles/$slug'
    | '/driver/create'
    | '/driver/register'
    | '/driver/wallet'
    | '/superadmin/bookings'
    | '/superadmin/drivers'
    | '/superadmin/trips'
    | '/superadmin/users'
    | '/admin/'
    | '/articles/'
    | '/driver/'
    | '/my-deliveries/'
    | '/send-package/'
    | '/superadmin/'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/my-deliveries/$deliveryId/pay'
    | '/send-package/$vanId/checkout'
    | '/send-package/$vanId/confirmation'
    | '/book/$vanId/'
    | '/driver/trips/'
    | '/send-package/$vanId/'
    | '/driver/trips/$tripId/edit'
    | '/driver/trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-vans'
    | '/my-bookings'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/schedules'
    | '/sign-in'
    | '/sign-up'
    | '/support'
    | '/terms-of-service'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/trips'
    | '/admin/users'
    | '/admin/wallets'
    | '/articles/$slug'
    | '/driver/create'
    | '/driver/register'
    | '/driver/wallet'
    | '/superadmin/bookings'
    | '/superadmin/drivers'
    | '/superadmin/trips'
    | '/superadmin/users'
    | '/admin'
    | '/articles'
    | '/driver'
    | '/my-deliveries'
    | '/send-package'
    | '/superadmin'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/my-deliveries/$deliveryId/pay'
    | '/send-package/$vanId/checkout'
    | '/send-package/$vanId/confirmation'
    | '/book/$vanId'
    | '/driver/trips'
    | '/send-package/$vanId'
    | '/driver/trips/$tripId/edit'
    | '/driver/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/driver'
    | '/my-deliveries'
    | '/superadmin'
    | '/find-vans'
    | '/my-bookings'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/schedules'
    | '/sign-in'
    | '/sign-up'
    | '/support'
    | '/terms-of-service'
    | '/driver/trips'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/trips'
    | '/admin/users'
    | '/admin/wallets'
    | '/articles/$slug'
    | '/driver/create'
    | '/driver/register'
    | '/driver/wallet'
    | '/superadmin/bookings'
    | '/superadmin/drivers'
    | '/superadmin/trips'
    | '/superadmin/users'
    | '/admin/'
    | '/articles/'
    | '/driver/'
    | '/my-deliveries/'
    | '/send-package/'
    | '/superadmin/'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/my-deliveries/$deliveryId/pay'
    | '/send-package/$vanId/checkout'
    | '/send-package/$vanId/confirmation'
    | '/book/$vanId/'
    | '/driver/trips/'
    | '/send-package/$vanId/'
    | '/driver/trips/$tripId/edit'
    | '/driver/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ArticlesRouteRoute: typeof ArticlesRouteRouteWithChildren
  DriverRouteRoute: typeof DriverRouteRouteWithChildren
  MyDeliveriesRouteRoute: typeof MyDeliveriesRouteRouteWithChildren
  SuperadminRouteRoute: typeof SuperadminRouteRouteWithChildren
  FindVansRoute: typeof FindVansRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchedulesRoute: typeof SchedulesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SupportRoute: typeof SupportRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  SendPackageIndexRoute: typeof SendPackageIndexRoute
  BookVanIdCheckoutRoute: typeof BookVanIdCheckoutRoute
  BookVanIdConfirmationRoute: typeof BookVanIdConfirmationRoute
  SendPackageVanIdCheckoutRoute: typeof SendPackageVanIdCheckoutRoute
  SendPackageVanIdConfirmationRoute: typeof SendPackageVanIdConfirmationRoute
  BookVanIdIndexRoute: typeof BookVanIdIndexRoute
  SendPackageVanIdIndexRoute: typeof SendPackageVanIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-vans': {
      id: '/find-vans'
      path: '/find-vans'
      fullPath: '/find-vans'
      preLoaderRoute: typeof FindVansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-deliveries': {
      id: '/my-deliveries'
      path: '/my-deliveries'
      fullPath: '/my-deliveries'
      preLoaderRoute: typeof MyDeliveriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/send-package/': {
      id: '/send-package/'
      path: '/send-package'
      fullPath: '/send-package/'
      preLoaderRoute: typeof SendPackageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-deliveries/': {
      id: '/my-deliveries/'
      path: '/'
      fullPath: '/my-deliveries/'
      preLoaderRoute: typeof MyDeliveriesIndexRouteImport
      parentRoute: typeof MyDeliveriesRouteRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/trips': {
      id: '/superadmin/trips'
      path: '/trips'
      fullPath: '/superadmin/trips'
      preLoaderRoute: typeof SuperadminTripsRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/drivers': {
      id: '/superadmin/drivers'
      path: '/drivers'
      fullPath: '/superadmin/drivers'
      preLoaderRoute: typeof SuperadminDriversRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/bookings': {
      id: '/superadmin/bookings'
      path: '/bookings'
      fullPath: '/superadmin/bookings'
      preLoaderRoute: typeof SuperadminBookingsRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/driver/wallet': {
      id: '/driver/wallet'
      path: '/wallet'
      fullPath: '/driver/wallet'
      preLoaderRoute: typeof DriverWalletRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/register': {
      id: '/driver/register'
      path: '/register'
      fullPath: '/driver/register'
      preLoaderRoute: typeof DriverRegisterRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/create': {
      id: '/driver/create'
      path: '/create'
      fullPath: '/driver/create'
      preLoaderRoute: typeof DriverCreateRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/driver/trips': {
      id: '/driver/trips'
      path: '/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverTripsRouteRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/send-package/$vanId/': {
      id: '/send-package/$vanId/'
      path: '/send-package/$vanId'
      fullPath: '/send-package/$vanId/'
      preLoaderRoute: typeof SendPackageVanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips/': {
      id: '/driver/trips/'
      path: '/'
      fullPath: '/driver/trips/'
      preLoaderRoute: typeof DriverTripsIndexRouteImport
      parentRoute: typeof DriverTripsRouteRoute
    }
    '/book/$vanId/': {
      id: '/book/$vanId/'
      path: '/book/$vanId'
      fullPath: '/book/$vanId/'
      preLoaderRoute: typeof BookVanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-package/$vanId/confirmation': {
      id: '/send-package/$vanId/confirmation'
      path: '/send-package/$vanId/confirmation'
      fullPath: '/send-package/$vanId/confirmation'
      preLoaderRoute: typeof SendPackageVanIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-package/$vanId/checkout': {
      id: '/send-package/$vanId/checkout'
      path: '/send-package/$vanId/checkout'
      fullPath: '/send-package/$vanId/checkout'
      preLoaderRoute: typeof SendPackageVanIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-deliveries/$deliveryId/pay': {
      id: '/my-deliveries/$deliveryId/pay'
      path: '/$deliveryId/pay'
      fullPath: '/my-deliveries/$deliveryId/pay'
      preLoaderRoute: typeof MyDeliveriesDeliveryIdPayRouteImport
      parentRoute: typeof MyDeliveriesRouteRoute
    }
    '/book/$vanId/confirmation': {
      id: '/book/$vanId/confirmation'
      path: '/book/$vanId/confirmation'
      fullPath: '/book/$vanId/confirmation'
      preLoaderRoute: typeof BookVanIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vanId/checkout': {
      id: '/book/$vanId/checkout'
      path: '/book/$vanId/checkout'
      fullPath: '/book/$vanId/checkout'
      preLoaderRoute: typeof BookVanIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips/$tripId/': {
      id: '/driver/trips/$tripId/'
      path: '/$tripId'
      fullPath: '/driver/trips/$tripId/'
      preLoaderRoute: typeof DriverTripsTripIdIndexRouteImport
      parentRoute: typeof DriverTripsRouteRoute
    }
    '/driver/trips/$tripId/edit': {
      id: '/driver/trips/$tripId/edit'
      path: '/$tripId/edit'
      fullPath: '/driver/trips/$tripId/edit'
      preLoaderRoute: typeof DriverTripsTripIdEditRouteImport
      parentRoute: typeof DriverTripsRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ArticlesRouteRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteRouteChildren: ArticlesRouteRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteRouteWithChildren = ArticlesRouteRoute._addFileChildren(
  ArticlesRouteRouteChildren,
)

interface DriverTripsRouteRouteChildren {
  DriverTripsIndexRoute: typeof DriverTripsIndexRoute
  DriverTripsTripIdEditRoute: typeof DriverTripsTripIdEditRoute
  DriverTripsTripIdIndexRoute: typeof DriverTripsTripIdIndexRoute
}

const DriverTripsRouteRouteChildren: DriverTripsRouteRouteChildren = {
  DriverTripsIndexRoute: DriverTripsIndexRoute,
  DriverTripsTripIdEditRoute: DriverTripsTripIdEditRoute,
  DriverTripsTripIdIndexRoute: DriverTripsTripIdIndexRoute,
}

const DriverTripsRouteRouteWithChildren =
  DriverTripsRouteRoute._addFileChildren(DriverTripsRouteRouteChildren)

interface DriverRouteRouteChildren {
  DriverTripsRouteRoute: typeof DriverTripsRouteRouteWithChildren
  DriverCreateRoute: typeof DriverCreateRoute
  DriverRegisterRoute: typeof DriverRegisterRoute
  DriverWalletRoute: typeof DriverWalletRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteRouteChildren: DriverRouteRouteChildren = {
  DriverTripsRouteRoute: DriverTripsRouteRouteWithChildren,
  DriverCreateRoute: DriverCreateRoute,
  DriverRegisterRoute: DriverRegisterRoute,
  DriverWalletRoute: DriverWalletRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteRouteWithChildren = DriverRouteRoute._addFileChildren(
  DriverRouteRouteChildren,
)

interface MyDeliveriesRouteRouteChildren {
  MyDeliveriesIndexRoute: typeof MyDeliveriesIndexRoute
  MyDeliveriesDeliveryIdPayRoute: typeof MyDeliveriesDeliveryIdPayRoute
}

const MyDeliveriesRouteRouteChildren: MyDeliveriesRouteRouteChildren = {
  MyDeliveriesIndexRoute: MyDeliveriesIndexRoute,
  MyDeliveriesDeliveryIdPayRoute: MyDeliveriesDeliveryIdPayRoute,
}

const MyDeliveriesRouteRouteWithChildren =
  MyDeliveriesRouteRoute._addFileChildren(MyDeliveriesRouteRouteChildren)

interface SuperadminRouteRouteChildren {
  SuperadminBookingsRoute: typeof SuperadminBookingsRoute
  SuperadminDriversRoute: typeof SuperadminDriversRoute
  SuperadminTripsRoute: typeof SuperadminTripsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteRouteChildren: SuperadminRouteRouteChildren = {
  SuperadminBookingsRoute: SuperadminBookingsRoute,
  SuperadminDriversRoute: SuperadminDriversRoute,
  SuperadminTripsRoute: SuperadminTripsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteRouteWithChildren = SuperadminRouteRoute._addFileChildren(
  SuperadminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ArticlesRouteRoute: ArticlesRouteRouteWithChildren,
  DriverRouteRoute: DriverRouteRouteWithChildren,
  MyDeliveriesRouteRoute: MyDeliveriesRouteRouteWithChildren,
  SuperadminRouteRoute: SuperadminRouteRouteWithChildren,
  FindVansRoute: FindVansRoute,
  MyBookingsRoute: MyBookingsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchedulesRoute: SchedulesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SupportRoute: SupportRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  SendPackageIndexRoute: SendPackageIndexRoute,
  BookVanIdCheckoutRoute: BookVanIdCheckoutRoute,
  BookVanIdConfirmationRoute: BookVanIdConfirmationRoute,
  SendPackageVanIdCheckoutRoute: SendPackageVanIdCheckoutRoute,
  SendPackageVanIdConfirmationRoute: SendPackageVanIdConfirmationRoute,
  BookVanIdIndexRoute: BookVanIdIndexRoute,
  SendPackageVanIdIndexRoute: SendPackageVanIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
