/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FindVansRouteImport } from './routes/find-vans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookVanIdIndexRouteImport } from './routes/book/$vanId/index'
import { Route as BookVanIdConfirmationRouteImport } from './routes/book/$vanId/confirmation'
import { Route as BookVanIdCheckoutRouteImport } from './routes/book/$vanId/checkout'

const FindVansRoute = FindVansRouteImport.update({
  id: '/find-vans',
  path: '/find-vans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVanIdIndexRoute = BookVanIdIndexRouteImport.update({
  id: '/book/$vanId/',
  path: '/book/$vanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVanIdConfirmationRoute = BookVanIdConfirmationRouteImport.update({
  id: '/book/$vanId/confirmation',
  path: '/book/$vanId/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVanIdCheckoutRoute = BookVanIdCheckoutRouteImport.update({
  id: '/book/$vanId/checkout',
  path: '/book/$vanId/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-vans': typeof FindVansRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/book/$vanId/': typeof BookVanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-vans': typeof FindVansRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/book/$vanId': typeof BookVanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-vans': typeof FindVansRoute
  '/book/$vanId/checkout': typeof BookVanIdCheckoutRoute
  '/book/$vanId/confirmation': typeof BookVanIdConfirmationRoute
  '/book/$vanId/': typeof BookVanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-vans'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/book/$vanId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-vans'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/book/$vanId'
  id:
    | '__root__'
    | '/'
    | '/find-vans'
    | '/book/$vanId/checkout'
    | '/book/$vanId/confirmation'
    | '/book/$vanId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindVansRoute: typeof FindVansRoute
  BookVanIdCheckoutRoute: typeof BookVanIdCheckoutRoute
  BookVanIdConfirmationRoute: typeof BookVanIdConfirmationRoute
  BookVanIdIndexRoute: typeof BookVanIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/find-vans': {
      id: '/find-vans'
      path: '/find-vans'
      fullPath: '/find-vans'
      preLoaderRoute: typeof FindVansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vanId/': {
      id: '/book/$vanId/'
      path: '/book/$vanId'
      fullPath: '/book/$vanId/'
      preLoaderRoute: typeof BookVanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vanId/confirmation': {
      id: '/book/$vanId/confirmation'
      path: '/book/$vanId/confirmation'
      fullPath: '/book/$vanId/confirmation'
      preLoaderRoute: typeof BookVanIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vanId/checkout': {
      id: '/book/$vanId/checkout'
      path: '/book/$vanId/checkout'
      fullPath: '/book/$vanId/checkout'
      preLoaderRoute: typeof BookVanIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindVansRoute: FindVansRoute,
  BookVanIdCheckoutRoute: BookVanIdCheckoutRoute,
  BookVanIdConfirmationRoute: BookVanIdConfirmationRoute,
  BookVanIdIndexRoute: BookVanIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
